// SimuPIC — lab boards for the "Placa" dropdown. Generated by the authoring tool.
// Overwritten by "Save labs.js"; commit + push to publish to students.
window.NP_LABS = [
  {"name":"TP - Simple","group":"Trabajos Prácticos","components":[{"type":"sevenseg","pins":["RB1","RB2","RB3","RB4","RB5","RB6","RB7"],"common":"","commonActiveLow":false,"label":"Dígito"},{"type":"button","pin":"RB0","activeLow":true,"label":"Pulsador"}]},
  {"name":"TP - Dificil","group":"Trabajos Prácticos","components":[{"type":"sevenseg","pins":["RB1","RB2","RB3","RB4","RB5","RB6","RB7"],"common":"RA0","commonActiveLow":false,"label":"D1"},{"type":"sevenseg","pins":["RB1","RB2","RB3","RB4","RB5","RB6","RB7"],"common":"RA1","commonActiveLow":false,"label":"D2"},{"type":"sevenseg","pins":["RB1","RB2","RB3","RB4","RB5","RB6","RB7"],"common":"RA2","commonActiveLow":false,"label":"D3"},{"type":"sevenseg","pins":["RB1","RB2","RB3","RB4","RB5","RB6","RB7"],"common":"RA3","commonActiveLow":false,"label":"D4"},{"type":"button","pin":"RA4","activeLow":false,"label":"START"},{"type":"button","pin":"RB0","activeLow":false,"label":"STOP/STEP"}]},
  {"name":"Test sin componentes","group":"Ejercitación","components":[]}
];
